FROM node:18-alpine

WORKDIR /app

# Copiar package.json
COPY package*.json ./

# Instalar dependencias
RUN npm i --omit=dev

# Copiar código del gateway
COPY gateway/index.js ./
COPY gateway/levelController.js ./
COPY gateway/proxy.js ./

# Instalar curl para healthchecks
RUN apk add --no-cache ca-certificates && update-ca-certificates
RUN apk add --no-cache curl

EXPOSE 3000

CMD ["node", "index.js"]
