FROM node:18-alpine

WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm i --omit=dev

# Copiar código fuente de servicios
COPY services/service-*.js ./

# Instalar curl para healthchecks
RUN apk add --no-cache ca-certificates && update-ca-certificates
RUN apk add --no-cache curl

EXPOSE 8080

# El comando específico se define en docker-compose.yml
CMD ["node", "service-full.js"]
